### PR TITLE
update-ui and some hover effect

### PR DESCRIPTION
**Pull request by Ambikadobhal**

### CODE REVIEW

**Comment by Aneeshaik** [comment]
Hey @Ambikadobhal! Can you please share the video of the changes you made?

**Comment by Ambikadobhal** [comment]
> Hey @Ambikadobhal! Can you please share the video of the changes you made?


Uploading Gym App - Google Chrome 2024-10-21 21-13-59.mp4…

**Comment by Ambikadobhal** [comment]
https://github.com/user-attachments/assets/9a0c308e-0bb2-4106-8158-b10c2c12e86f

**Comment by Ambikadobhal** [comment]
Can you please accept my pr

**Comment by Aneeshaik** [comment]
> Can you please accept my pr

Hey @Ambikadobhal! I appreciate your effort towards this project. But the hover effect on the navbar is looking old model and hover effect on the images in the workout's section is some what more. But, your home page idea is amazing. I am accepting your PR. If you want you can again work on navbar and workout section hover. Thanks for your efforts

**Pull request merged**
